main: me.stupiddrew9.reactchat.React
name: ReactChat
version: 0.2.0
commands:
  reactchat: 
permissions:
  reactchat.react:
    description: Allows a user to react to chat messages
  reactchat.receive:
    description: Allows users to react to users that have permission